kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-9-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: /data/postgres-9-pv                   # minikube
    path: /usr/local/var/k8s-data/postgres-9-pv # docker-for-mac
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-9-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: postgres-9-pv
