kind: Service
apiVersion: v1
metadata:
  name: postgres-9-service
spec:
  type: NodePort
  selector:
    app: postgres-9-container
  ports:
    - protocol: TCP
      nodePort: 30432
      port: 5432
      targetPort: 5432
